import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/components/modules/AuthProvider";
import { ReduxProvider } from "@/redux/ReduxProvider";
import BodyDarker from "@/components/modules/BodyDarker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
        {children}
        <BodyDarker/>
        <AuthProvider/>
        <Toaster
          position="bottom-left"
          reverseOrder={false}
          toastOptions={{
            duration: 7000,
          }}
        />
        </ReduxProvider>
      </body>
    </html>
  );
}
